### ISSUE TITLE
[Question] Will this be updated for Django 4.1?

### ISSUE THREAD

**Issue by simkimsia** [jambonsw/django-improved-user#251]
Just a question. Will this be updated for Django 4.1? or just 4.2?

**Comment by deronnax** [comment]
@jambonrose would you transfer ownership to @jazzband if you can't maintain the project anymore?

**Comment by ulgens** [comment]
+1 for the question and the suggestion.

**Comment by jambonrose** [comment]
Hi folks,

Sorry for the delayed response.

Are you having issues with the package? I've been using the library on Django 4.x without issue.

Or were you looking for more up-to-date compatibility information and PyPI classifiers (as seen in v2.1)?

I'm trying to understand what maintenance you're expecting.

Thanks.

**Comment by simkimsia** [comment]
> Or were you looking for more up-to-date compatibility information and PyPI classifiers (as seen in v2.1)?
> 


This

Thank you for updating

It also be good if you can update the compatibility once every 6 months or so 

I often skip open source that have not shown any commits for more than a year unless I absolutely cannot do without it

**Comment by simkimsia** [comment]
Closed by https://github.com/jambonrose/django-improved-user/releases/tag/v2.1.0
