### ISSUE TITLE
Unable to Import Mix-in Classes independently of package

### ISSUE THREAD

**Issue by jambonrose** [jambonsw/django-improved-user#36]
## Specifications

- Platform/System: macOS 10.11
- Python Version: 3.6
- Django Version: 1.11
- Improved User Version: 0.5.3

## Expected Behavior

In a Django project: I expect to be able to import the mix-in model classes without needing to add improved_user to `INSTALLED_APPS`.

## Actual Behavior

Django evaluates the `User` model and attempts to add it to the database.

```pytb
  File "/Users/andrew/Development/verified-auth/.tox/py36-django111-unit/lib/python3.6/site-packages/verified_auth/models.py", line 7, in <module>
    from improved_user.models import (
  File "/Users/andrew/Development/verified-auth/.tox/py36-django111-unit/lib/python3.6/site-packages/improved_user/models.py", line 167, in <module>
    class User(AbstractUser):
  File "/Users/andrew/Development/verified-auth/.tox/py36-django111-unit/lib/python3.6/site-packages/django/db/models/base.py", line 118, in __new__
    "INSTALLED_APPS." % (module, name)
RuntimeError: Model class improved_user.models.User doesn't declare an explicit app_label and isn't in an application in INSTALLED_APPS.
```

## Context

I am using the provided mix-in classes and manager to create a new User model in a separate app.

```python
from django.contrib.auth.models import (
    AbstractBaseUser, PermissionsMixin,
)
from django.db import models
from django.utils.translation import ugettext_lazy as _
from improved_user.models import (
    DjangoIntegrationMixin, EmailAuthMixin, UserManager,
)
```

The import above causes the traceback listed above.

If I add `improved_user` to `INSTALLED_APPS` I believe Django will pollute my database with a table for `User`, which I am seeking to replace.

## Steps to Reproduce the Problem

1. Create a new Django project with a new Django app
2. Install `django-improved-user==0.5.3`
3. Import the tools (as seen in the code above)
4. Run migrations or tests to cause the `RunTimeError`

**Comment by securedirective** [comment]
I concur with this issue. I just ran into it myself and was about to email you to see if perhaps I was doing something wrong.

Is there any currently working way of extending django-improved-user as the documentation implies?

**Comment by jambonrose** [comment]
Not currently, but I am planning to fix the issue tomorrow!

**Comment by jambonrose** [comment]
.... ok, that's not quite true.

You can use all the mix-ins if you add the app to `INSTALLED_APPS`. The catch is that you will end up with an extra model (the improved user) in your database. As long as you don't point the user model setting to the improved user, and instead point it to your own User, you won't be introducing any long term problems. *In theory*, once the next version is out, you'll be able to simply remove the app from `INSTALLED_APPS`, and migrations will take care of the rest (***in theory*** -I have not tested this!).

**Comment by securedirective** [comment]
Nope. I've followed your documentation as closely as I can and I only get errors from Django, even on a fresh project. Would you like me to write up a separate bug report describing what I see, even prior to your new version?

I'm hoping this is just a documentation+newbie problem. :)

**Comment by jambonrose** [comment]
Oh, there's definitely a problem, so even following documentation, I expect that it'd be difficult to get around this bug.

The branch I just pushed appears to fix the problem. Unfortunately, it's not quite ready to be integrated into the main branch, because these changes completely break the documentation.

The `example_extension_project` directory on the `fix_issue_36_move_model_mixins` branch should prove to be a guide for how to build a new User model from this new code. I'm planning to fix the documentation and add new documentation on this subject tomorrow.

Let's hold off on opening a new bug report for the moment. If you are still seeing errors once I merge the `fix_issue_36_move_model_mixins` branch in, then I welcome a new issue. Thanks!

**Comment by securedirective** [comment]
Sounds like a plan.

**Comment by jambonrose** [comment]
@securedirective: take a look at the new documentation found in [here](http://django-improved-user.readthedocs.io/en/latest/create_custom_user_with_mixins.html). Let me know what you think!

For the moment, to use the new code, you'll need to install the code directly from github (the `development` branch).

If you are still seeing an error that reads `RuntimeError: Model class improved_user.models.User doesn't declare an explicit app_label and isn't in an application in INSTALLED_APPS.`, please reopen this issue and describe how you got the error. If you are seeing a different error, please open a new issue.

Thanks for all your help!
