### ISSUE TITLE
Case sensitivity of email addresses

### ISSUE THREAD

**Issue by securedirective** [jambonsw/django-improved-user#44]
## Specifications

- Platform/System: Ubuntu 16.04
- Python Version: 3.5.2
- Django Version: 1.11
- Improved User Version: 0.5.3

## Expected Behavior
I would expect default behavior to be case-insensitive.

## Actual Behavior
After creating a "user@test.com" account, I cannot create another with the same email. But this user model *does* allow me to create "USER@test.com" without any error message. The result is two separate accounts whose emails would actually reach the same inbox, due to ISPs ignoring case.

## Context
[RFC 5321 Part 2.4](https://tools.ietf.org/rfc/rfc5321.txt) states that only the domain portion of an email is case-insensitive. So `django-improved-user` is compliant. But since most ISPs treat emails as fully case-insensitive, using this package could end up with unexpected results, compared to the authentication behavior of most websites out there today.

Are there any plans to do this here too? Perhaps a standard-compliant case-sensitive version of `EmailAuthMixin` and `UserManager` could be provided in case the developer prefers that?

If you agree with this route, I don't mind doing some research on how case-insensitive uniqueness could be accomplished.

**Comment by jambonrose** [comment]
Thank you very much for the bug report!

One of the key goals for `django-improved-user` is to closely-mimic Django behavior with only several key enhancements. Django sticks to the email spec:

```pycon
>>> # in the shell of a new Django project
>>> from django.contrib.auth.models import User
>>> User.objects.create_user('user1', 'user@test.com')
<User: user1>
>>> User.objects.create_user('user2', 'USER@test.com')
<User: user2>
```

I am therefore unwilling to change the behavior of the supplied improved user model. However, I think it is well-worth documenting this behavior.

With all that said, I find the suggestion of a case-insensitive option to be interesting. Let me think about the best way to go about this, and whether the long-term benefits outweigh the costs, before I get back to you.

**Comment by securedirective** [comment]
Thank you for the feedback.

FYI, here is an option I came up from my project. It forces all emails to lowercase.

1. Contents of `fields.py`:
```
from django.db import models
class LowerEmailField(models.EmailField):
    def __init__(self, *args, **kwargs):
        super(LowerEmailField, self).__init__(*args, **kwargs)

    def from_db_value(self, value, expression, connection, context):
        if value is None:
            return value
        return value.lower()

    def get_prep_value(self, value):
        value = super(LowerEmailField, self).get_prep_value(value)
        return value.lower()
```

2. Contents of `models.py`:
```
from .fields import LowerEmailField
[...]
class EmailAuthMixin(models.Model):
    [...]
    email = LowerEmailField(_('email address'), max_length=254, unique=True)
    [...]
```

3. Optionally, remove all use of `normalize_email` as it's no longer needed.

**Comment by jambonrose** [comment]
Direct link for convenience: http://django-improved-user.readthedocs.io/en/latest/email_warning.html

**Comment by bukowa** [comment]
Google does not follow RFC at looks like they are fine 👍

**Comment by ge0rg** [comment]
@securedirective just a small nitpick that [the `context` argument was deprecated in django 2.0 and removed in 3.0](https://docs.djangoproject.com/en/3.1/releases/2.0/#deprecated-features-2-0), and `get_prep_value` also needs a None-check of value.
